# yml  yaml
# Yet Another Markup Language

spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.92.140
    port: 5672
    username: admin
    password: admin
#    virtual-host: /wht/jj   分支路径
      
#--  
server:
  port: 8001
  
#--
#server:
#  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true # 使用ip进行注册
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port} # 界面列表中显示的格式也显示ip
 